Add Express JS server
Gemeente-DenHaag/mijngemeente-gateway pull request #36
Opened 2021-03-05 14:56 UTC by bddjong

2021-03-06 13:20 UTC, joostvanviegen reviewed
At what point will we start writing tests for functionality like this?

2021-03-06 13:31 UTC, bddjong commented
> At what point will we start writing tests for functionality like this?

Good question. It was decided (during the sprint review (05/03/21)) that testing and logging implementations are out of scope until we reach a more definitive stage of adding functionality to the gateway. This and a few upcoming issues are highly depended on for the development of an end-to-end proof of concept. This will give us a better picture of how the gateway will function. Testing should be relevant from that point on. 

This concern is noted and can be tracked with the following issue:
#34 - Establish logging strategy
#33 - Establish testing strategy
#35 - Continuous deployment

(A continuous integration issue should be created after the testing strategy is done).

2021-03-06 13:39 UTC, DanielvanVliet reviewed
Add a guide to the readme how to get .env to work, which files to create and what data is required.

2021-03-06 13:39 UTC, DanielvanVliet commented on src/auth/ITokenAuthenticator.ts
> +    GenerateToken: () => string;
Suggestion: use a type alias to represent a JWTToken.
```suggestion
    GenerateToken: () => Token;
    
  ...
  type Token = string;
```

2021-03-10 13:14 UTC, bddjong commented on src/auth/ITokenAuthenticator.ts
> +    GenerateToken: () => string;
Good suggestion! I added a JWT type alias for a string. Decided on naming it `JWT` instead of Token since it's less ambiguous about the type of Token.

2021-03-10 16:36 UTC, joostvanviegen requested changes
I would like to see a bit more comments to explain non self explanatory code.
The rest of my requests for changes are quite nitpicky.

2021-03-10 16:36 UTC, joostvanviegen commented on src/auth/MockTokenAuthenticator.ts
> +  private getIssuedAtTime = (): number => Math.floor(Date.now() / 1000);
Why is this conversion necessary? Looking at this code I cannot tell, we might need to add a comment for this since it isn't self explanatory.

2021-03-10 16:36 UTC, joostvanviegen commented on src/auth/MockTokenAuthenticator.ts
> +  private getIssuedAtTime = (): number => Math.floor(Date.now() / 1000);
Also, we are not really consistent with newlines. The other changed files have statements like this spread over multiple lines.

2021-03-10 16:36 UTC, joostvanviegen commented on src/auth/tokens/JWTGenerator.ts
> +    return jwt.sign(JSON.stringify(payload), secret);
To be consistent with the other changes we might need to add a few newlines.

2021-03-10 17:13 UTC, DanielvanVliet commented on src/auth/tokens/JWTGenerator.ts
> +  static Generate(payload: any, secret: string): JWT {
Can this any be avoided?

2021-03-11 11:47 UTC, bddjong commented on src/auth/tokens/JWTGenerator.ts
> +  static Generate(payload: any, secret: string): JWT {
JWTGenerator is a utility class. From my personal experience it would be strange make it non-static. (If thats what you're referring to)

2021-03-11 11:58 UTC, bddjong commented on src/auth/MockTokenAuthenticator.ts
> +  private getIssuedAtTime = (): number => Math.floor(Date.now() / 1000);
> Why is this conversion necessary?

Date.now() returns milliseconds. RFC standard for JWT defines that `iat` and `exp` values use the seconds since epoch, not milliseconds. That said, perhaps the function should be called `getCurrentTimeInSeconds`. I think that would make the code self-explanatory, and we can avoid comments :D

> The other changed files have statements like this spread over multiple lines

Which files and statement are you referring to?

2021-03-11 12:00 UTC, bddjong commented on src/auth/tokens/JWTGenerator.ts
> +  static Generate(payload: any, secret: string): JWT {
The alternative is accepting a string, and expecting implementers to stringify their payload when calling the Generate fucntion.

2021-03-11 12:01 UTC, bddjong commented on src/auth/tokens/JWTGenerator.ts
> +    return jwt.sign(JSON.stringify(payload), secret);
How (and why) would you split the code up with newlines? Could you provide an example?

2021-03-12 12:16 UTC, mjcarsjens commented on src/auth/MockTokenAuthenticator.ts
> +  private getIssuedAtTime = (): number => Math.floor(Date.now() / 1000);
I think renaming it to `getCurrentTimeInSeconds` indeed clarifies why this is done.

2021-03-12 12:16 UTC, mjcarsjens commented on src/auth/tokens/JWTGenerator.ts
> +  static Generate(payload: any, secret: string): JWT {
My personal preference does not go out to stringifying the payload beforehand, I feel like this should be done in the Generate function as is the case right now.

An alternative to avoid this any is to create a new type specifying what the payload should (and optionally can) include, for example:

`export type Payload = {
    client_id: string,
    iss: string,
    iat: number,
    user_id: string,
    user_representation: string
};`

2021-03-12 12:16 UTC, mjcarsjens commented on src/auth/tokens/JWTGenerator.ts
> +    return jwt.sign(JSON.stringify(payload), secret);
To me splitting this up into multiple lines seems a bit unnecessary as it is quite a short statement, and I feel like this would only reduce readability. However, if this is not in line with the code style splitting it up could be considered.

2021-03-12 12:32 UTC, mjcarsjens approved these changes
Looks good to me, left some small comments but overall it works as it should

2021-03-13 11:25 UTC, bddjong commented on src/auth/tokens/JWTGenerator.ts
> +  static Generate(payload: any, secret: string): JWT {
Changed the type to the more restrictive object type instead of any. (Which is also what the underlying token library uses). I don't think a token generator should set restrictions to the payload. Ideally, we would have several fields that the payload should and could include, but that would remove the possibility of adding other claims to the JWT.

2021-03-13 11:25 UTC, bddjong commented on README.md
> +2. Install npm go [here](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm) for instructions. Make sure to install version `14` or higher.
Resolved :)

2021-03-13 11:25 UTC, bddjong commented on package.json
> +  "license": "EUPL",
Thanks, didn't notice that. Fixed!

2021-03-13 12:31 UTC, DanielvanVliet approved these changes

2021-03-13 13:13 UTC, joostvanviegen approved these changes

2021-03-13 13:23 UTC, merged