Feature/#5 get all zaken
Gemeente-DenHaag/mijngemeente-gateway pull request #37
Opened 2021-03-20 15:01 UTC by DanielvanVliet

Resolves #5 

The endpoint is at `/zaken` with optionally one `bsn` query parameter.
The endpoint expects a jwt token which is validated using a middleware (thanks @joostvanviegen).

There is currently no middleware for decryption of the token but this can be added later when necessary.

2021-03-20 15:08 UTC, bddjong requested changes

2021-03-20 15:08 UTC, bddjong commented on package.json
> +    "axios": "^0.21.1",
Axios isn't used and can be removed

2021-03-20 15:08 UTC, bddjong commented on src/auth/tokens/JWTChecker.ts
> +    static Check(token: JWT, secret: string): boolean
I think calling this util function `verify` or `verifyToken` would better describe it's purpose. 

Additionally (and this is partly my fault) I'm not sure if PascalCasing for method names in Typescript is a nice convention. Regardless of what we choose, the casing is currently inconsistent and should be made consistent.

2021-03-24 09:14 UTC, DanielvanVliet commented on src/auth/tokens/JWTChecker.ts
> +    static Check(token: JWT, secret: string): boolean
resolved

2021-03-24 09:53 UTC, bddjong approved these changes

2021-03-24 09:53 UTC, bddjong commented on src/controllers/ZakenController.ts
> +  if (query.bsn !== undefined) {
Eventually, the BSN should not be part of the query. Right now, we're not validating that the person sending the request is actually authorized to get data for that BSN. The following steps should eventually be implemented

1. Mock authentication is called
2. A (test) BSN is added to the token payload when it's generated
3. The token is sent to the client, and the client sends it with every request
4. When the gateway receives a request, it gets the BSN from the decrypted and verified token

I'm okay with keeping the current implementation so that the PWA is no longer blocked. But just so we're aware.

2021-03-24 11:10 UTC, GewoonMaarten requested changes

2021-03-24 11:10 UTC, GewoonMaarten commented on src/middleware/JWTAuthMiddleware.ts
> +    if (jwt !== null && jwt !== undefined) {
```suggestion
    if (jwt != null) { 
```

2021-03-24 11:10 UTC, GewoonMaarten commented on src/controllers/ZakenController.ts
> +  if (token === undefined || token === null) {
`null` is the same as `undefined`. Also no value type can be implicitly coerced to `null` type, so `===` is unnecessarily.
```suggestion
  if (token == null) {
```

2021-03-24 11:10 UTC, GewoonMaarten commented on src/controllers/ZakenController.ts
> +  if (query.bsn !== undefined) {
```suggestion
  if (query.bsn != null) {
```

2021-03-24 11:26 UTC, DanielvanVliet commented on src/controllers/ZakenController.ts
> +  if (token === undefined || token === null) {
I don't think they're the same, token can be either a string or undefined. A null check will not cover the undefined case.
But the null case might not be necessary.

2021-03-24 11:28 UTC, DanielvanVliet commented on src/index.ts
> +  .use("/zaken", ZaakRouter);
No, since the ZaakRouter contains a middleware (for a jwt token) that Authrouter does not need.

2021-03-24 12:03 UTC, GewoonMaarten approved these changes

2021-03-24 12:06 UTC, GewoonMaarten commented on src/index.ts
> +  .use("/zaken", ZaakRouter);
`use()` returns an Express app. `app.use().use()` and `app.use(); app.use();` is the same thing.

2021-03-24 12:10 UTC, merged